### ISSUE TITLE
Derive Keystore public key from secret key

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#1028]
Context: #1013

Currently we're parsing it from the file, but the value could be wrong. Also, deriving it from the secret enables us to add an additional check by comparing both the parsed and derived values.

**Comment by guha-rahul** [comment]
Can i take it?

**Comment by MegaRedHand** [comment]
Sure! Go ahead! Let me know if you need some pointers.

**Comment by guha-rahul** [comment]
> Sure! Go ahead! Let me know if you need some pointers.
Hey sorry for the late reply but dump as many pointers as you like .

**Comment by MegaRedHand** [comment]
* The keystore is in `lib/keystore.ex`.
* We currently parse the public key here:
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/24acec6627229953886c0d6203b9298ebd0a6392/lib/keystore.ex#L26-L27
* The idea is to derive the key from the secret key before.
* You might need to add a function to `lib/bls.ex` for that (keep in mind it's a NIF, so actual code is in Rust and lives inside `native/bls_nif`)
