### ISSUE TITLE
Implement `pbkdf2` on `Keystore`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#1029]
Context: #1013

Currently, we only support the Scrypt key derivation function. We want to support `pbkdf2` since that one's also mentioned in [ERC-2335](https://eips.ethereum.org/EIPS/eip-2335).

**Comment by okekefrancis112** [comment]
am I to write the pbkdf from scratch using "elixir" and plug the keystore into it?

**Comment by MegaRedHand** [comment]
No need. We can add https://hex.pm/packages/pbkdf2_elixir as a dependency for that. Most of the work is calling that here:
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/a30602e4a5809b8950273d2da143644738c531f3/lib/keystore.ex#L67

**Comment by MegaRedHand** [comment]
Hey there, @okekefrancis112 ! We ended up implementing this in #1078. Sorry for the trouble!
