### ISSUE TITLE
Make `pubkey` field optional

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#1084]
Once #1067 is merged, we can make the `pubkey` field optional on keystores. For that, we'd need to change this `fetch!` here:

https://github.com/lambdaclass/lambda_ethereum_consensus/blob/5160683ae3834fb3eb45daaa556b46e73d2dd544/lib/keystore.ex#L27

**Comment by artemd24** [comment]
I'd like to tackle this!
