### ISSUE TITLE
Add actual error handling in libp2p NIF

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#110]
Currently, the libp2p NIF just prints the error from the Go side, and returns a NULL handle:

https://github.com/lambdaclass/lambda_ethereum_consensus/blob/2197d9e667a7f76325709f5fe0c12b9474d5468a/native/libp2p_nif/main.go#L124-L128

We should handle it in a better way. One thing I can think of is receiving a pointer to a `char*`, and setting it with an error string when something fails.

**Comment by karasakalmt** [comment]
Can I take and try to resolve the issue?

**Comment by MegaRedHand** [comment]
Sure!

**Comment by karasakalmt** [comment]
Hey @MegaRedHand I will need to test the part I changed after I am done with this do you have any suggestion for me to debug it better, or is there a file I can only execute the operations in libp2p.

**Comment by MegaRedHand** [comment]
The NIF has unit tests in `test/unit/libp2p_test.exs`, and there are integration tests and examples in `test/integration/libp2p_test.exs`. Feel free to add some of your own 😄

**Comment by MegaRedHand** [comment]
Hey @karasakalmt ! How's work going? Did you manage to make some progress?

**Comment by karasakalmt** [comment]
hey @MegaRedHand got so busy lately :(. Will be done by tomorrow or Thursday!

**Comment by MegaRedHand** [comment]
I had to add something like this for one of the functions (but later removed it). Maybe it will help:

https://github.com/lambdaclass/lambda_ethereum_consensus/blob/4ee27a4b51ba46b4f04510d67ef5a0f5eb48e1cd/native/libp2p_nif/main.go#L490-L504

**Comment by MegaRedHand** [comment]
Hey @karasakalmt ! We are looking into changing the NIF for an Erlang Port, so most of the interface will not stay the same as it is now. I suggest working on another issue in the meantime.

**Comment by karasakalmt** [comment]
Hey! alright then I am unassigning myself for a while then I can come back later

**Comment by MegaRedHand** [comment]
No longer relevant
