### ISSUE TITLE
Implement first endpoint `/eth/v1/beacon/states/{state_id}/root` for Beacon API

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#131]
Following the Beacon API specs we need to implement the first endpoint enabling us to query the root of the latest Beacon state using `/eth/v1/beacon/states/{state_id}/root`

**Comment by mpaulucci** [comment]
Closed by https://github.com/lambdaclass/lambda_ethereum_consensus/pull/218
