### ISSUE TITLE
Implement `Bls.eth_aggregate_pubkeys` function

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#136]
Implementation can be inspired in: https://github.com/lambdaclass/lambda_ethereum_consensus/pull/129

Test case format available [here](https://github.com/ethereum/consensus-specs/blob/ff9963fb0b54863102cdff511ad622e69543a829/tests/formats/bls/eth_aggregate_pubkeys.md). Test data available in the [consensus-spec-tests repo](https://github.com/ethereum/consensus-spec-tests).

Acceptance criteria: Spec tests for bls `eth_aggregate_pubkeys` should pass.

**Comment by h3lio5** [comment]
can I take this?

**Comment by mpaulucci** [comment]
Hi @h3lio5 are you still working on this issue?

**Comment by h3lio5** [comment]
Apologies for the delay! I’ll finish it today and make a PR.
