### ISSUE TITLE
Implement `Bls.eth_fast_aggregate_verify` function

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#137]
Implementation can be inspired in: https://github.com/lambdaclass/lambda_ethereum_consensus/pull/129

Acceptance criteria: Spec tests for bls `eth_fast_aggregate_verify` should pass.

**Comment by f3r10** [comment]
can I take this please?

**Comment by MegaRedHand** [comment]
Sure! Go ahead!

**Comment by f3r10** [comment]
In order to complete this, it is necessary to complete this one #133 :sweat_smile:

**Comment by f3r10** [comment]
So, if you do mind, I would also take #133

**Comment by MegaRedHand** [comment]
No problem! For context: [`Bls.eth_fast_aggregate_verify` is just a wrapper to `bls.fast_aggregate_verify` ](https://github.com/ethereum/consensus-specs/blob/dev/specs/altair/bls.md#eth_fast_aggregate_verify)
