### ISSUE TITLE
Downloaded test vectors should go inside `spec/test` folder

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#146]
We're currently downloading the spec test vectors to the root of the project. I think it would be better to download them and uncompress them inside a special folder, i.e `test/spec/vectors`. The main reason is not to pollute the root of the project and avoid confusion (for example, we have `test` and `tests`).

Acceptance criteria:
- Download test vectors to a special folder inside `test/spec`. See `make download-vectors`
- Update spec test generator to look for tests inside that folder: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/test/spec/utils/generator.ex
- Optional: do we want to remove `*.tar.gz` files after decompressing them?
- Update `.gitignore` if applicable

**Comment by aikooo7** [comment]
Good morning @mpaulucci I'm good to try to do this, can you give me a little more explanation of where to find what you specifically in the first and second steps?

**Comment by mpaulucci** [comment]
If you go to the `Makefile` you will find the script which is `make download-vectors`, there you can specify where to download or move the files.  On the second step, you will have to update the path here: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/test/spec/utils/generator.ex#L43

Does this answer your questions?
