### ISSUE TITLE
Simplify SSZ types (Minimal vs Mainnet) configurations

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#148]
In Elixir, we don't care if a type is Minimal or Mainnet, since we usually don't deal with size restrictions. We do on the Rust side though, since there we do the encoding & decoding.

Would it be possible to just create one type on the Elixir side, and then choose the Mainnet vs Minimal Rust struct based on a configuration that we pass in the NIF or through a resource?

**Comment by phklive** [comment]
This can be closed i believe.
