### ISSUE TITLE
Libp2p: validate messages received from peers

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#164]
This can be done with [`(*PubSub).RegisterTopicValidator`](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub#PubSub.RegisterTopicValidator), which should receive a [`ValidatorEx`](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub#ValidatorEx) so we can differentiate between _REJECT_ and _IGNORE_ actions.

**Comment by namn-grg** [comment]
Can I try solving this?

**Comment by MegaRedHand** [comment]
This issue is a reminder, mostly. It is really big, as it requires implementing both the logic for message validation and the logic for interfacing between the libp2p NIF (which we are also moving to a port). I suggest you work on another issue (we are working on opening new ones right now 😓).

**Comment by namn-grg** [comment]
No problem, I'll check another issues
