### ISSUE TITLE
Add OpenApiSpex to the phoenix endpoints

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#165]
The [OpenApiSpex](https://github.com/open-api-spex/open_api_spex) projects allows for input validation using open api schemas that describe the fields and types we accept as part of a query. This issue will be considered finished once all implemented endpoints use Open API spex. After this issue is finished, all new endpoints should validate inputs with OpenApiSpex.

**Comment by okekefrancis112** [comment]
Please can i work on this?

**Comment by phklive** [comment]
Sure assigned!
