### ISSUE TITLE
[Snappy] Implement Snappy framing format in Elixir

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#224]
_Needs some thinking_

Since the framing format is fairly simple, it's worth considering implementing [the framing format](https://github.com/google/snappy/blob/main/framing_format.txt) ourselves in Elixir (using `:snappyer` for the underlying block compression) to remove the complexity of interfacing with Rust code. This should simplify the implementation of a true streaming de/compression (as of now, it needs the whole stream in memory to work).

**Comment by mpaulucci** [comment]
is this a duplicate of https://github.com/lambdaclass/lambda_ethereum_consensus/issues/46 ?

**Comment by MegaRedHand** [comment]
My bad. I'll leave this one open and close the other one.

**Comment by mpaulucci** [comment]
Work has been started on this PR: https://github.com/lambdaclass/lambda_ethereum_consensus/pull/543
