### ISSUE TITLE
[Building blocks] Implement shuffling algorithm

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#242]
To be able to decide how to divide the validators into committees, we need a shuffling algorithm. This is the one specified in the spec:

https://github.com/lambdaclass/lambda_ethereum_consensus/blob/5e97070e691fdbc685b48d73c1e01472e3f06dd5/docs/specs/beacon-chain.md?plain=1#L1149-L1172

This is the corresponding spec test: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/shuffling

Additional read if needed: https://eth2book.info/capella/part2/building_blocks/shuffling/

Actual test cases can be seen in `lambda_ethereum_consensus/tests/minimal/phase0/shuffling/core`

Acceptance criteria:
- Implement `compute_shuffled_index` in Elixir according to the spec
- Implement `shuffling` spec test runner
- All shuffling tests should pass

**Comment by yash-atreya** [comment]
@mpaulucci I can take this

**Comment by mpaulucci** [comment]
go for it!

**Comment by yash-atreya** [comment]
Hey @mpaulucci, sorry for the inconvenience.
Have unassigned myself.

**Comment by mpaulucci** [comment]
@Godspower-Eze assigning you

**Comment by Godspower-Eze** [comment]
Okay.

Which file should I creat this in?

**Comment by MegaRedHand** [comment]
I think something like `lib/lambda_ethereum_consensus/state_transition/shuffling.ex` would be ok. We can always move it later.

**Comment by Godspower-Eze** [comment]
Okay. Thanks
