### ISSUE TITLE
[Config] Add Eth Spec configuration

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#243]
We want to start using the Elixir configuration api https://hexdocs.pm/elixir/main/Config.html to store the Eth Spec configurations.

For that we want to start with something similar to what lighthouse does, which is having the configuration in a yaml file and reading it on compilation time.

For example, this is the sepolia config: https://github.com/sigp/lighthouse/blob/stable/common/eth2_network_config/built_in_network_configs/sepolia/config.yaml

We should store these in `config/{chain_name}/config.yaml`. 

We want to read the configs like `Application.fetch_env!(:eth_spec, :preset_name)` # mainnet.

The app should include a command line option `--network=sepolia` and it should load the appropriate spec config on runtime. It should default to mainnet.

**Comment by phklive** [comment]
Going to take it and close this before pushing further with #236, to be able to use the config var in the internal functions.
