### ISSUE TITLE
[epoch processing] Implement `process_inactivity_updates`

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#255]
This is the function

https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/docs/specs/beacon-chain.md?plain=1#L2238-L2253

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/epoch_processing

Acceptance criteria:
- Run corresponding spec tests by removing https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/test/spec/runners/epoch_processing.ex#L12.

**Comment by MegaRedHand** [comment]
Sure!

**Comment by f3r10** [comment]
Is it ok if I place the helper functions like `get_current_epoch` `compute_epoch_at_slot` in `LambdaEthereumConsensus.Beacon.HelperFunctions` module.
I am seeing that in other pull requests are placing similar helper functions in different places :thinking:

**Comment by phklive** [comment]
Hey @f3r10, we will divide these function into 4 different files: 
- Accessors: get_ funcs
- Mutators: no common example
- Predicates: is_ funcs
- Misc: other funcs
