### ISSUE TITLE
[epoch processing] Implement `process_slashings`

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#258]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/docs/specs/beacon-chain.md?plain=1#L2466-L2477

Acceptance criteria:
- Run corresponding spec tests by removing https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/test/spec/runners/epoch_processing.ex#L15

**Comment by ayushm2003** [comment]
would like to take this up

**Comment by ayushm2003** [comment]
hey, this function requires a few helper functions from the beacon-chain spec doc. Am implementing those first, should I create a new issue?

**Comment by mpaulucci** [comment]
I wouldn't create an issue for a helper function unless it's a big one. Which one are you talking about?

**Comment by ayushm2003** [comment]
`get_current_epoch`, `get_total_balance`, `get_total_active_balance`, `is_active_validator`, `get_active_validator_indices`

some of these likely overlap with other PRs, will look into it and add the ones remaining as part of this issue itself

**Comment by phklive** [comment]
@ayushm2003 how is it going with this issue? Are you able to go forward ?

**Comment by ayushm2003** [comment]
is there some way to test the outputs of the helper functions?

**Comment by phklive** [comment]
> is there some way to test the helper functions?

Implementing unit tests. When you understand the helper you should be able to build some unit test to verify it's correct functionality.
