### ISSUE TITLE
[epoch processing] Implement `process_slashings_reset`

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#261]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/docs/specs/beacon-chain.md?plain=1#L2534-L2539

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/epoch_processing

Acceptance criteria:
- Run corresponding spec tests by removing https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/test/spec/runners/epoch_processing.ex#L18

**Comment by sm-stack** [comment]
Could I take this?

**Comment by mpaulucci** [comment]
yes, go for it!

**Comment by sm-stack** [comment]
Is it right to implement [this](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#compute_epoch_at_slot) at `lib/lamda_ethereum_consensus/beacon/helper_function.ex` to handle current epoch number? Or is there anywhere to query current epoch info from beacon state?

**Comment by mpaulucci** [comment]
@all-contributors please add @sm-stack for code
