### ISSUE TITLE
[epoch processing] Implement `process_historical_summaries_update`

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#263]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/docs/specs/beacon-chain.md?plain=1#L2573-L2583

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/epoch_processing

Acceptance criteria:
- Run corresponding spec tests by removing https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/test/spec/runners/epoch_processing.ex#L20

**Comment by mpaulucci** [comment]
Careful with calculating the hash tree root, we need to specify max size

**Comment by karasakalmt** [comment]
May I take this one?
