### ISSUE TITLE
[epoch processing] Implement `process_participation_flag_updates`

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#265]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/docs/specs/beacon-chain.md?plain=1#L2497-L2501

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/epoch_processing

Acceptance criteria:
- Run corresponding spec tests by removing https://github.com/lambdaclass/lambda_ethereum_consensus/blob/66059de3653c17ae620ce2aca2db61c558057f6a/test/spec/runners/epoch_processing.ex#L22

**Comment by Godspower-Eze** [comment]
I can take this

**Comment by mpaulucci** [comment]
Hey @Godspower-Eze maybe we can leave this one for someone who is looking for a first issue? Would you mind taking this one for example? https://github.com/lambdaclass/lambda_ethereum_consensus/issues/242

**Comment by karasakalmt** [comment]
May I take this?

**Comment by phklive** [comment]
Yes
