### ISSUE TITLE
[tracking] Epoch processing implementations

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#274]
Tracking issue for the Epoch processing functionality

- [x] #254
- [x] #255
- [x] #256
- [x] #257
- [x] #258
- [x] #259
- [x] #260
- [x] #261
- [x] #262
- [x] #263
- [x] #265
- [x] #267

**Comment by mpaulucci** [comment]
This seems to be completed 🙌
