### ISSUE TITLE
Patch doesn't work in spec tests

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#289]
When trying to patch some code, the following error appears:

```
 ** (exit) exited in: GenServer.call(Patch.Mock.Supervisor, {:start_child, {{Patch.Mock.Server, :start_link, [EpochProcessingTestRunner, []]}, :temporary, 5000, :worker, [Patch.Mock.Server]}}, :infinity)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     code: SpecTestGenerator.generate_tests("mainnet", "capella")
```

There's a minimal reproduction of the error in [this branch](https://github.com/lambdaclass/lambda_ethereum_consensus/tree/test-gen-patch-error).

The error seems to indicate that the patch call is being run in compile time instead of at runtime. This might also be related to #288

**Comment by MegaRedHand** [comment]
This was fixed by the spec-test refactor
