### ISSUE TITLE
Add jwt.hex import from file for Engine API EL <> CL

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#30]
https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md

The execution layer and consensus layer clients SHOULD accept a configuration parameter: jwt-secret, which designates a file containing the hex-encoded 256 bit secret key to be used for verifying/generating JWT tokens.

If such a parameter is not given, the client SHOULD generate such a token, valid for the duration of the execution, and SHOULD store the hex-encoded secret as a jwt.hex file on the filesystem. This file can then be used to provision the counterpart client.

If such a parameter is given, but the file cannot be read, or does not contain a hex-encoded key of 256 bits, the client SHOULD treat this as an error: either abort the startup, or show error and continue without exposing the authenticated port.

**Comment by MegaRedHand** [comment]
@namn-grg If you want to work on this, it should be doable. #161 adds code to receive info from CLI, so you can use it as a guideline.

**Comment by MegaRedHand** [comment]
This was addressed in #521, right @mpaulucci ?
