### ISSUE TITLE
[operations] Implement `process_attestation`

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#300]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/dd0a0523e6be2a21fa3f6a96d4466926307d236c/docs/specs/beacon-chain.md?plain=1#L2761-L2795

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/operations

Acceptance criteria:

- Run corresponding spec tests

**Comment by sm-stack** [comment]
Can I take this?

**Comment by phklive** [comment]
Sure assigned

**Comment by phklive** [comment]
I would also recommend going through this handbook before starting your implementation: https://github.com/lambdaclass/lambda_ethereum_consensus/pull/295/files

PS: open the graph and let me know what you think / if it's useful to you

**Comment by phklive** [comment]
@sm-stack how is it going with this issue, are you able to go forward ?

**Comment by phklive** [comment]
<img width="1680" alt="SCR-20231017-lffd" src="https://github.com/lambdaclass/lambda_ethereum_consensus/assets/42912740/491dc124-4f18-489f-9114-a2a74a25fea9">

As you can see this is not the easiest implementation, I might cut down on the task and start with implementations of helper functions first before going into the full function.

**Comment by sm-stack** [comment]
> @sm-stack how is it going with this issue, are you able to go forward ?

Thanks for checking in. Currently implementing a few helper functions at `accessors.ex` and `predicates.ex`. I have a 2 question about implementation, which is
1. Where can I get `DOMAIN_BEACON_ATTESTER`? I need that when implementing `get_beacon_committee`, and maybe I add it to the config?
2. Could I generate `operations.ex` at `lib/lambdaclass_ethereum_consensus/state_transition` for `process_attestation` function, or should it be at different path? 

> <img alt="SCR-20231017-lffd" width="1680" src="https://user-images.githubusercontent.com/42912740/275801056-491dc124-4f18-489f-9114-a2a74a25fea9.png">
> As you can see this is not the easiest implementation, I might cut down on the task and start with implementations of helper functions first before going into the full function.

Also that will be great. I'm working on the helper functions now, so will focus on implementing them first if you do so.

**Comment by MegaRedHand** [comment]
For 1, you should do like #309 and declare them in the `Constants` module: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/acb74b5544f3a18ec7529808c72805c0513489ef/lib/constants.ex

**Comment by phklive** [comment]
> > @sm-stack how is it going with this issue, are you able to go forward ?
> 
> Thanks for checking in. Currently implementing a few helper functions at `accessors.ex` and `predicates.ex`. I have 2 questions about implementation, which is
> 
> 1. Where can I get `DOMAIN_BEACON_ATTESTER`? I need that when implementing `get_beacon_committee`, and maybe I add it to the config?
> 2. Could I generate `operations.ex` at `lib/lambdaclass_ethereum_consensus/state_transition` for `process_attestation` function, or should it be at different path?
> 
> > <img alt="SCR-20231017-lffd" width="1680" src="https://user-images.githubusercontent.com/42912740/275801056-491dc124-4f18-489f-9114-a2a74a25fea9.png">
> > As you can see this is not the easiest implementation, I might cut down on the task and start with implementations of helper functions first before going into the full function.
> 
> Also that will be great. I'm working on the helper functions now, so will focus on implementing them if you do so.

Absolutely you should generate a operations.ex file at the location you pointed.
