### ISSUE TITLE
[operations] Implement `process_attester_slashing`

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#301]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/dd0a0523e6be2a21fa3f6a96d4466926307d236c/docs/specs/beacon-chain.md?plain=1#L2709-L2724

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/operations

Acceptance criteria:
- Run corresponding spec tests

**Comment by karasakalmt** [comment]
Hey may I get this one? also in the other issue I saw 
https://github.com/lambdaclass/lambda_ethereum_consensus/issues/300#issuecomment-1766348829
seems like 2nd question remained unanswered could you answer that as well?

**Comment by phklive** [comment]
> Hey may I get this one? also in the other issue I saw [#300 (comment)](https://github.com/lambdaclass/lambda_ethereum_consensus/issues/300#issuecomment-1766348829) seems like 2nd question remained unanswered could you answer that as well?

Question answered.

**Comment by karasakalmt** [comment]
Must have missed it though may I get the issue 😄
