### ISSUE TITLE
[operations] Implement `process_block_header`

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#302]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/dd0a0523e6be2a21fa3f6a96d4466926307d236c/docs/specs/beacon-chain.md?plain=1#L2616-L2638

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/operations

Acceptance criteria:
- Run corresponding spec tests

**Comment by MegaRedHand** [comment]
@phklive Are you working on this?

**Comment by phklive** [comment]
I was working on it indeed if you are willing to take it you can I have not been able to PR it for now.

**Comment by MegaRedHand** [comment]
@Godspower-Eze Do you want to work on this one?

**Comment by Godspower-Eze** [comment]
Yeah, I can.
