### ISSUE TITLE
[operations] Implement `process_deposit`

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#303]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/dd0a0523e6be2a21fa3f6a96d4466926307d236c/docs/specs/beacon-chain.md?plain=1#L2874-L2895

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/operations

Acceptance criteria:
- Run corresponding spec tests

**Comment by karasakalmt** [comment]
I can take this

**Comment by phklive** [comment]
Yes
