### ISSUE TITLE
[operations] Implement `process_sync_aggregate`

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#306]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/dd0a0523e6be2a21fa3f6a96d4466926307d236c/docs/specs/beacon-chain.md?plain=1#L2949-L2975

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/operations

Acceptance criteria:
- Run corresponding spec tests

**Comment by Godspower-Eze** [comment]
I can take this.
