### ISSUE TITLE
[Spec test perf] Make spec test generation per-handler

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#335]
After #333 is finished and the test generation is per-handler, the next step is to have it generated per-handler. This would mean that instead of building a single for-loop for all cases in a test and then dynamically dispatching to different handler functions, we should make the a macro to generate all tests for a single handler. The goal of this is that if a developer is working on a handler, then that handler should be the single point of recompilation and not the whole runner module.

This is part of #288

**Comment by mpaulucci** [comment]
Closing these as not important after discussing with @Arkenan
