### ISSUE TITLE
Handle responses with missing blocks

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#364]
See https://github.com/lambdaclass/lambda_ethereum_consensus/pull/341#discussion_r1376725377

Basically, an error in a block can indicate a missing block. In that case, we should make it return the parsed response to the caller, but also add a wrapper function that takes care of requesting those blocks again.

**Comment by mpaulucci** [comment]
This has been fixed in https://github.com/lambdaclass/lambda_ethereum_consensus/pull/452/files
