### ISSUE TITLE
Review result unwrapping on infallible primitives

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#379]
Some primitives cannot fail unless something goes terribly wrong, for example:
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/907a456d19079dd66315c21c86c620a224ab2703/lib/lambda_ethereum_consensus/beacon/helper_functions.ex#L36-L46

In this case `Ssz.hash_tree_root` can only fail if the `ssz_object` isn't SSZ serializable/hashable, which can't happen since we are working on internal (already parsed) data. We should simplify this by adding some infallible (`_!`) variants, or by somehow modeling the SSZ-enabled types.

**Comment by mpaulucci** [comment]
Fixed in https://github.com/lambdaclass/lambda_ethereum_consensus/pull/397
