### ISSUE TITLE
Decouple `BitVector` internal representation from SSZ NIF's

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#401]
Context: https://github.com/lambdaclass/lambda_ethereum_consensus/pull/388#discussion_r1385098847

In the SSZ NIF we are using the `BitVector`'s inner representation, which is equal to the SSZ representation (little-endian), while we are assuming a big-endian representation on the `LambdaEthereumConsensus.Utils.BitVector` module.

**Comment by MegaRedHand** [comment]
While implementing, we should also remove this:
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/d27906aa1581c7665734e404d384a22beff2ad62/lib/lambda_ethereum_consensus/state_transition/accessors.ex#L397-L406

**Comment by Arkenan** [comment]
Some more clarification:

1. `BitVector`'s inner representation shouldn't be important for the API (we should only interact with `set`, `clear`, `set?`, etc), but it should be *consistent*.
2. Right now, the representation is not consistent: it does shifts as a big-endian representation, but doesn't take care of the reversal.

For now, we should take the bitlists as they come (little-endian-bit-order) and modify the API calls to accomodate to that. For a second iteration, we could evaluate treating `bitlists` as integers and using `BitWise` operations, as encoding and decoding is standard little-endian-byte-order.

**Comment by Arkenan** [comment]
Revisited the code, and I'll actually change the bit order when constructing the bitvector type. We can then change back when converting to bytes. The biggest reason for this is that little-endian-byte-order will not allow us to have bitstrings with the exact amount of bits we need, for that we would need either little-endian-bit-order or big-endian (which is both byte and bit order always).

**Comment by Arkenan** [comment]
More info: I ran a benchmark on reversing bytes with three different methods:

1. little-endian parsing + big-endian encoding (that is, using a number as an intermediate representation)
2. Covnerting the binary to a list, reversing, and back to a binary.
3. Using bytestring comprehension.

These were the results:

```

Name                    ips        average  deviation         median         99th %
number            2101.20 K        0.48 μs  ±8219.84%        0.38 μs        0.50 μs
list               310.38 K        3.22 μs   ±405.99%        3.04 μs        6.58 μs
comprehension      119.76 K        8.35 μs   ±175.94%        7.96 μs       15.21 μs

Comparison: 
number            2101.20 K
list               310.38 K - 6.77x slower +2.75 μs
comprehension      119.76 K - 17.55x slower +7.87 μs
```

Using a number is way more performant, which leads me to believe that if we'll be using a number as an intermediate representation already, we should use it as the internal representation always. Will do benchmarks in a different issue/PR.

**Comment by Arkenan** [comment]
More info: I ran a benchmark on reversing bytes with three different methods:

1. little-endian parsing + big-endian encoding (that is, using a number as an intermediate representation)
2. Covnerting the binary to a list, reversing, and back to a binary.
3. Using bytestring comprehension.

These were the results:

```

Name                    ips        average  deviation         median         99th %
number            2101.20 K        0.48 μs  ±8219.84%        0.38 μs        0.50 μs
list               310.38 K        3.22 μs   ±405.99%        3.04 μs        6.58 μs
comprehension      119.76 K        8.35 μs   ±175.94%        7.96 μs       15.21 μs

Comparison: 
number            2101.20 K
list               310.38 K - 6.77x slower +2.75 μs
comprehension      119.76 K - 17.55x slower +7.87 μs
```

Using a number is way more performant, which leads me to believe that if we'll be using a number as an intermediate representation already, we should use it as the internal representation always. Will do benchmarks in a different issue/PR.
