### ISSUE TITLE
The spectests aren't regenerated automatically

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#406]
Sometimes the tests aren't regenerated automatically. To fix this manually, run `make clean-tests` to remove them.

**Comment by mpaulucci** [comment]
@MegaRedHand this should be fixed with https://github.com/lambdaclass/lambda_ethereum_consensus/pull/464 right?

**Comment by mpaulucci** [comment]
Going to close this, feel free to reopen if I missed something
