### ISSUE TITLE
[SSZ] Encode/decode a simple container

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#416]
## Goals

The goal of this issue is to encode Validator, which is an example of a container that has different types in it, but none of them is another container. The type is described in the specs as:

```python
class Validator(Container):
    pubkey: BLSPubkey
    withdrawal_credentials: Bytes32  # Commitment to pubkey for withdrawals
    effective_balance: Gwei  # Balance at stake
    slashed: boolean
    # Status epochs
    activation_eligibility_epoch: Epoch  # When criteria for activation were met
    activation_epoch: Epoch
    exit_epoch: Epoch
    withdrawable_epoch: Epoch  # When validator can withdraw funds
```

We need to:

- Add a `Container` behavior module which defines a `schema()` callback.
- Make the `Validator` module implement `Container` behavior, by implementing a `schema()` function.
- in the ssz library, we need an `encode(container, module) when is_map(container)` function that calls `encode(container, module.schema())`. In this way we won't need to add an encoding function for each module, we just need to define their schemas in the container module, and the module itself will act as a schema. 
- Same with the decoding function.

**Comment by Godspower-Eze** [comment]
I can take this

**Comment by f3r10** [comment]
I am already working on this :sweat_smile:
