### ISSUE TITLE
Implement `Status` Req/Resp handler

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#421]
The general request and response content is:

```
(
  fork_digest: ForkDigest
  finalized_root: Root
  finalized_epoch: Epoch
  head_root: Root
  head_slot: Slot
)
```

We already have some hardcoded answer, but we should dynamically update it, since we have the functions to do it.

Some of them are:
- `Helpers.get_head`, to get the head root and slot.
- `Misc.compute_fork_digest`, using the head state to get the `genesis_validators_root`.
- `Store.get_finalized_checkpoint` to get the epoch and root.

**Comment by f3r10** [comment]
can I take this issue?

**Comment by Arkenan** [comment]
Hi! Sorry, I had talked to Mete about this a couple of days ago and I just wasn't able to assign this to him yet.
