### ISSUE TITLE
Use `Types` in type specs

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#432]
In files like `constants.ex` we usually see stuff like 

```elixir
@spec domain_beacon_proposer() :: <<_::32>>
def domain_beacon_proposer, do: <<0, 0, 0, 0>>
```

which is a `DomainType` for the spec. However, we annotate it as a generic `<<_::32>>`. We have a file called `mod.ex` with `SszTypes` module which has the definition:

```elixir
@type domain_type :: bytes4
```

We should export those types so that we can correctly annotate the value as:

```elixir
@spec domain_beacon_proposer() :: Ssz.domain_type()
def domain_beacon_proposer, do: <<0, 0, 0, 0>>
```

The same goes for every other type in `SszTypes` module.

**Comment by MegaRedHand** [comment]
Let's close this and tackle each case as we find them
