### ISSUE TITLE
Implement `beacon_blocks_by_root/2` incoming request

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#446]
Spec: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/docs/specs/p2p-interface.md#beaconblocksbyroot-v2

This one is quite similar to the `beacon_blocks_by_range/2` which has already been implemented: https://github.com/lambdaclass/lambda_ethereum_consensus/pull/363

**Comment by h3lio5** [comment]
assign me please
