### ISSUE TITLE
[tracking] Sanity slots spec tests

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#451]
These are all the test cases corresponding to the sanity runner (for slots). Please comment the one you are working on below so we avoid many people working on the same ones.

**Slot Cases**
- [x] Empty epoch
- [x] Slots 1
- [x] Slots 2
- [x] Over epoch boundary
- [x] Historical accumulator
- [x] Double empty epoch

**Comment by MegaRedHand** [comment]
Done 🎉
