### ISSUE TITLE
Implement `sync` spec test runner.

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#461]
This one is is the same as the fork choice one

https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/sync

**Comment by MegaRedHand** [comment]
NOTE: we need to add some functionality to the fork-choice runner to enable this.

**Comment by mpaulucci** [comment]
We do have that functionality now, we can start working on this ticket
