### ISSUE TITLE
Add function to shuffle an entire list instead of one element at a time

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#467]
See this comment by lighthouse:

https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/consensus/swap_or_not_shuffle/src/shuffle_list.rs#L52-L78C1

We should also have something like this.

**Comment by h3lio5** [comment]
can I take this one?

**Comment by MegaRedHand** [comment]
Hey @h3lio5 ! Sorry, but I'm gonna take this issue. As part of the optimizations I'm working on, I'll implement this and check if it reduces the amount of processing in `process_attestation`
