### ISSUE TITLE
[SSZ] Support merkleization for basic types (ints, bools)

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#481]
We need to add support for `hash_tree_root(n)`, with `n` a `uintN` or `boolean`.

Spec is [here](https://github.com/ethereum/consensus-specs/blob/b2f2102dad0cd8b28a657244e645e0df1c0d246a/ssz/simple-serialize.md#merkleization)

We are still in the process of adding spec-tests for SSZ+hashing.

**Comment by MegaRedHand** [comment]
@Godspower-Eze You should work on this one first
