### ISSUE TITLE
[SSZ] Support merkleization for lists

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#482]
We need to add support for `hash_tree_root([...])`

Spec is [here](https://github.com/ethereum/consensus-specs/blob/b2f2102dad0cd8b28a657244e645e0df1c0d246a/ssz/simple-serialize.md#merkleization)

We are still in the process of adding spec-tests for SSZ+hashing.

**Comment by MegaRedHand** [comment]
Sure! I'll update the description a bit

**Comment by MegaRedHand** [comment]
Done! But we should start by #481
