### ISSUE TITLE
Bitlist utils

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#512]
We should add a module with utils for manipulating bitstring-encoded bitlists.

Candidate functions for this module are:

https://github.com/lambdaclass/lambda_ethereum_consensus/blob/ae5c2a0195b9c285dfe6ab346e1cd2d944aebe2e/lib/lambda_ethereum_consensus/state_transition/operations.ex#L869-L873

**Comment by Arkenan** [comment]
Some more comments on this:
- `Bitlist.new(binary, max_size)` which:
  - Uses the trailling bit to calculate the length.
  - Reverses the bytes the same way the bitvector does and is represented.
  - Its internal representation will be {binary, max_size} so checks can be performed if needed.
- `Bitlist.to_bytes()` adds the traililng bit.

Up to now, it's mostly moving the code from ssz_ex to this new module and adding the byte reversal, which is missing. It also needs all of the same functionality that bitvector has with regards to:

- Checking if a single bit is set or clear with `set?(list, index)`.
- Setting a single bit with `set(list, index)` and `clear(list, index)`.
