### ISSUE TITLE
[SSZ] Write schemas for all containers

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#513]
Full list can be found in the [Eth2Book](https://eth2book.info/capella/part3/containers/), but here's a checkboxed copy for reference and progress update:

Misc:

- [x] [Fork](https://eth2book.info/capella/part3/containers/dependencies/#fork)
- [x] [ForkData](https://eth2book.info/capella/part3/containers/dependencies/#forkdata)
- [x] [Checkpoint](https://eth2book.info/capella/part3/containers/dependencies/#checkpoint)
- [x] [Validator](https://eth2book.info/capella/part3/containers/dependencies/#validator)
- [x] [AttestationData](https://eth2book.info/capella/part3/containers/dependencies/#attestationdata)
- [x] [IndexedAttestation](https://eth2book.info/capella/part3/containers/dependencies/#indexedattestation)
- [x] [PendingAttestation](https://eth2book.info/capella/part3/containers/dependencies/#pendingattestation)
- [x] [Eth1Data](https://eth2book.info/capella/part3/containers/dependencies/#eth1data)
- [x] [HistoricalBatch](https://eth2book.info/capella/part3/containers/dependencies/#historicalbatch)
- [x] [DepositMessage](https://eth2book.info/capella/part3/containers/dependencies/#depositmessage)
- [x] [DepositData](https://eth2book.info/capella/part3/containers/dependencies/#depositdata)
- [x] [BeaconBlockHeader](https://eth2book.info/capella/part3/containers/dependencies/#beaconblockheader)
- [x] [SyncCommittee](https://eth2book.info/capella/part3/containers/dependencies/#synccommittee)
- [x] [SigningData](https://eth2book.info/capella/part3/containers/dependencies/#signingdata)
- [x] [Withdrawal](https://eth2book.info/capella/part3/containers/dependencies/#withdrawal)
- [x] [HistoricalSummary](https://eth2book.info/capella/part3/containers/dependencies/#historicalsummary)

Beacon operations:

- [x] [ProposerSlashing](https://eth2book.info/capella/part3/containers/operations/#proposerslashing)
- [x] [AttesterSlashing](https://eth2book.info/capella/part3/containers/operations/#attesterslashing)
- [x] [Attestation](https://eth2book.info/capella/part3/containers/operations/#attestation)
- [x] [Deposit](https://eth2book.info/capella/part3/containers/operations/#deposit)
- [x] [VoluntaryExit](https://eth2book.info/capella/part3/containers/operations/#voluntaryexit)
- [x] [SyncAggregate](https://eth2book.info/capella/part3/containers/operations/#syncaggregate)
- [x] [BLSToExecutionChange](https://eth2book.info/capella/part3/containers/operations/#blstoexecutionchange)

Beacon Blocks

- [x] [BeaconBlockBody](https://eth2book.info/capella/part3/containers/blocks/#beaconblockbody)
- [x] [BeaconBlock](https://eth2book.info/capella/part3/containers/blocks/#beaconblock)

Beacon State

- [x] [BeaconState](https://eth2book.info/capella/part3/containers/state/#beaconstate)
- [x] [Historical Note](https://eth2book.info/capella/part3/containers/state/#historical-note)

Execution

- [x] [ExecutionPayload](https://eth2book.info/capella/part3/containers/execution/#executionpayload)
- [x] [ExecutionPayloadHeader](https://eth2book.info/capella/part3/containers/execution/#executionpayloadheader)

**Comment by MegaRedHand** [comment]
Done
