### ISSUE TITLE
Generate jwt secret if not specified

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#532]
Continuation of #30

https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md

The execution layer and consensus layer clients SHOULD accept a configuration parameter: jwt-secret, which designates a file containing the hex-encoded 256 bit secret key to be used for verifying/generating JWT tokens.

If such a parameter is not given, the client SHOULD generate such a token, valid for the duration of the execution, and SHOULD store the hex-encoded secret as a jwt.hex file on the filesystem. This file can then be used to provision the counterpart client.

If such a parameter is given, but the file cannot be read, or does not contain a hex-encoded key of 256 bits, the client SHOULD treat this as an error: either abort the startup, or show error and continue without exposing the authenticated port.

**Comment by mpaulucci** [comment]
I've looked at Lighthouse, Prysm and Lodestar.

It seems that none of them generate a token if the jwt file is not generated. The problem with generating the jwt automatically is that both the consensus and the execution clients might generate their own jwt file and they won't be able to communicate properly.

Lighthouse error
```
Error! Please set either --execution-jwt file_path or --execution-jwt-secret-key directly via cli when using --execution-endpoint
```

Prysm error:
```
ERROR powchain: Could not connect to execution client endpoint error=could not verify execution chain ID as your connection is not authenticated. If connecting to your execution client via HTTP, you will need to set up JWT authentication. See our documentation here https://docs.prylabs.network/docs/execution-node/authentication: 401 Unauthorized: missing token
```

**Comment by MegaRedHand** [comment]
Seems like a good enough reason. We should provide a way to skip generating the JWT when developing, though.

**Comment by MegaRedHand** [comment]
Reworked in #541
