### ISSUE TITLE
Implement `notify_forkchoice_updated` function that calls the Engine API 

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#534]
See: https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_forkchoiceupdatedv2

Preliminary read: 
- https://hackmd.io/@danielrachi/engine_api#Block-validation
- https://eth2book.info/capella/part3/forkchoice/bellatrix/#notify_forkchoice_updated

To calculate the safe block:
- https://eth2book.info/capella/part3/safe-block/
- https://github.com/ethereum/consensus-specs/blob/dev/fork_choice/safe-block.md

For `payloadAttributes` field, let's send `null` for now. `payloadAttributes` is set when building a block.

**Comment by f3r10** [comment]
could I take this issue? or is there another priority issue?

**Comment by Arkenan** [comment]
Assigned!
