### ISSUE TITLE
Allow running the node without an execution client

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#541]
Currently, running `make iex` results in the error message:

```
[error] No jwt file provided. Please specify the path to fetch it from via the --execution-jwt flag.
```

We should make this _jwt_ flag optional (but keep the warning).

**Comment by MegaRedHand** [comment]
Already addressed in #542. We should, however, refactor the whole JWT thing.

A good solution would be:
* to mock the execution client when "debug flags" are used
* to require a JWT otherwise
* to document both use cases, and how to generate a JWT

**Comment by MegaRedHand** [comment]
wdyt @mpaulucci ?

**Comment by mpaulucci** [comment]
Im all for it!

**Comment by MegaRedHand** [comment]
Split into: #579 #580 #581
