### ISSUE TITLE
Use computed `fork_digest` instead of hardcoded one.

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#554]
We have some places where we use a hardcoded fork digest, see https://github.com/search?q=repo%3Alambdaclass%2Flambda_ethereum_consensus%20BBA4DA96&type=code

This digest corresponds to capella in Mainnet, but we should be able to calculate it for any fork of any network.

We should compute the fork digest for the current slot, like lighthouse does: https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/consensus/types/src/chain_spec.rs#L218-L228

We also need to update this function with the fork digest for the current slot: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/d1375bfc8767c0fd350c0fa92e9b3cc66b52be74/lib/lambda_ethereum_consensus/fork_choice/helpers.ex#L18

**Comment by MegaRedHand** [comment]
Note that we already have the functions to compute the fork digest, as called here:

https://github.com/lambdaclass/lambda_ethereum_consensus/blob/d1375bfc8767c0fd350c0fa92e9b3cc66b52be74/lib/lambda_ethereum_consensus/fork_choice/helpers.ex#L18-L19

**Comment by mpaulucci** [comment]
Blocked by #540
