### ISSUE TITLE
[Beacon API] id_to_state_root function

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#557]
We have different ways to address states:

- [ ] `"genesis"` literal. This represents the genesis state according to the node.
- [ ] `"justified"`. This represents the last justified state according to the node.
- [ ] `"finalized"`. This represents the last finalized state according to the node.
- [ ] `"head"` string. The current head state according to the node.
- [ ] by a root. The most direct addressing is the root of a state.

We can have a parser in `beacon_api/utils.ex`:

```elixir
parse_id("genesis") -> :genesis
parse_id("justified") -> :justified
parse_id("finalized") -> :finalized
parse_id("head") -> :head
parse_id("0x" <> hex_root) -> <<root>>
parse_id(other) -> :invalid_id
```

We can then have a `root_by_id(id)` function that takes any of the previous results and returns a root that can be used to get a state using the db.

```elixir
root = Utils.parse_id(id) |> ForkChoice.Utils.root_by_id()
```

The checkboxes in the issue mark the completion of each specific parsing and root_by_id clause. This task will be considered finished when the `get_state_root` endpoint of the beacon api uses this function.

**Comment by f3r10** [comment]
there is an additional case when the `binary` does not start with `0x` it could be the slot that has to be parsed into ~Types.slot`
