### ISSUE TITLE
Remove race condition on checkpoint-sync's state and block fetching

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#565]
We currently are fetching the block and state concurrently. We should later check that the two correspond to the same slot, and if not, fetch the correct block/state by specifying the slot in the requested url.

**Comment by mpaulucci** [comment]
it is verified here: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/lib/lambda_ethereum_consensus/fork_choice/helpers.ex#L33

**Comment by MegaRedHand** [comment]
We should retry in case it fails. Currently we are just stopping the node
