### ISSUE TITLE
Add SSZ container:  `SignedBLSToExecutionChange`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#59]
Depends on: #58

Follow these instructions: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md

#### `SignedBLSToExecutionChange`

```python
class SignedBLSToExecutionChange(Container):
    message: BLSToExecutionChange
    signature: BLSSignature
```

**Comment by h3lio5** [comment]
can I take this please?

**Comment by MegaRedHand** [comment]
Sure!
