### ISSUE TITLE
[SSZ] Serialization/deserialization of vectors

### ISSUE THREAD

**Issue by Godspower-Eze** [lambdaclass/lambda_ethereum_consensus#599]
## Description

We currently have serialization and deserialization of lists but not for vectors.

Since vectors are unavailable in Elixir, we can achieve this by using wrappers and lists as the underlying collection.

This would also make [hash tree root of vectors](https://github.com/lambdaclass/lambda_ethereum_consensus/issues/598) possible.

This is also closely tied to [this](https://github.com/lambdaclass/lambda_ethereum_consensus/issues/593).

**Comment by MegaRedHand** [comment]
> Since vectors are unavailable in Elixir, we can achieve this by using wrappers and lists as the underlying collection.

This isn't needed. Since we are using "schemas" we already have a way to specify the SSZ type independently of the underlying Elixir type.

**Comment by Godspower-Eze** [comment]
Gotcha. Would there be one for lists too?

**Comment by MegaRedHand** [comment]
Yes. You can see some examples here:
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/f2fe509e7eeb9fe3391b9a55d29d26104332ecd2/test/unit/ssz_ex_test.exs#L87-L93

**Comment by f3r10** [comment]
I think all the logic is already created for supporting vectors. It would be necessary to add these functions:
```elixir
def decode(binary, {:vector, basic_type, size}), do: decode_list(binary, basic_type, size) 

def encode(list, {:list, basic_type, size}), do: encode_fixed_size_list(list, basic_type, size)
```

**Comment by f3r10** [comment]
btw not related but once `vectors` are supported, it would be possible to enable all the spec tests on https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/lib/spec/runners/ssz_generic.ex

**Comment by Godspower-Eze** [comment]
> Yes. You can see some examples here:
> 
> https://github.com/lambdaclass/lambda_ethereum_consensus/blob/f2fe509e7eeb9fe3391b9a55d29d26104332ecd2/test/unit/ssz_ex_test.exs#L87-L93
> 
> The `{:list, {:int, 32}, 3}` part is the "schema" that specifies the SSZ types to be used.

Gotcha. I thought you were taking about something else.

**Comment by Godspower-Eze** [comment]
I will work on this
