### ISSUE TITLE
Add beacon API tests

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#613]
#612

**Comment by f3r10** [comment]
could it take this one?

**Comment by MegaRedHand** [comment]
Yes, sure! (I meant to to assign it to you, not to me 😅)

**Comment by f3r10** [comment]
@MegaRedHand  This is what we would need, right? https://hexdocs.pm/phoenix/testing.html

**Comment by MegaRedHand** [comment]
Yes. Although we'll probably have to mock the DB calls with `patch`
