### ISSUE TITLE
Add SSZ container: `AttesterSlashing`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#63]
Depends on: #78

Follow these instructions: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md

#### `AttesterSlashing`

```python
class AttesterSlashing(Container):
    attestation_1: IndexedAttestation
    attestation_2: IndexedAttestation
```

**Comment by h3lio5** [comment]
can I take this ser?

**Comment by MegaRedHand** [comment]
Go ahead! 👍
