### ISSUE TITLE
Allow going from `state_root` to `state` in the DB

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#637]
For some endpoints we need to fetch the state from the state's root. This is currently not possible, because we index the states by the corresponding block's root.

**Comment by karasakalmt** [comment]
just curious
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/445154b04d358a6e1612a677c83ee4a453fa365c/lib/lambda_ethereum_consensus/store/state_store.ex#L29-L35
isn't this function fetches the state by state root using DB?

I may not understood the issue correctly sorry for that

**Comment by MegaRedHand** [comment]
The `root` in that function is the block's root, not the state's
