### ISSUE TITLE
Add SSZ container: `Deposit`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#65]
Follow these instructions: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md

#### `Deposit`

```python
class Deposit(Container):
    proof: Vector[Bytes32, DEPOSIT_CONTRACT_TREE_DEPTH + 1]  # Merkle path to deposit root
    data: DepositData
```

**Comment by f3r10** [comment]
I'd like to tackle this!

**Comment by MegaRedHand** [comment]
Sure! Go ahead!

**Comment by f3r10** [comment]
I am going to stash the changes and start right away with #66

**Comment by f3r10** [comment]
it looks like DepositData is already implemented. I am going to try to add Deposit
