### ISSUE TITLE
Store execution status for a block

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#651]
We should know what the status of the execution layer is for a Block. Possible statuses: Valid, Invalid, Optimistic.

Also, when querying a block through the Beacon Api, we should return the appropriate `execution_optimistic` flag.

EDIT: We can start by storing the execution status only in memory inside of the fork choice.

**Comment by karasakalmt** [comment]
Hey @mpaulucci status is returning `"VALID" | "INVALID" | "SYNCING" | "ACCEPTED" | "INVALID_BLOCK_HASH"` in most of the cases are you sure optimistic flag returns in status been reading the specs but couldn't find the related field

**Comment by mpaulucci** [comment]
We don't need to store the execution status, we can derive it
