### ISSUE TITLE
Add SSZ container: `VoluntaryExit`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#66]
Follow these instructions: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md

#### `VoluntaryExit`

```python
class VoluntaryExit(Container):
    epoch: Epoch  # Earliest epoch when voluntary exit can be processed
    validator_index: ValidatorIndex
```

**Comment by MegaRedHand** [comment]
Note: @f3r10 is working on this issue (can't assign because of GH restrictions)

**Comment by f3r10** [comment]
This one is quite interesting both fields `epoch` and `validator_index` are `u64`  therefore VoluntaryExit does not require a lifetime, but because of how the macro `gen_struct!`  is defined it is necessary to pass a lifetime. :thinking:

**Comment by f3r10** [comment]
I tried to create another macro that does not require that lifetime but because of how the encoding part works with `rustler::term` that lifetime it is necessary

**Comment by f3r10** [comment]
Thanks :+1: It works perfectly... I have to learn about rust macros :sweat_smile:

**Comment by MegaRedHand** [comment]
Me too! I used declarative macros (`macro_rules!`) just because I knew them, but they are quite restrictive for some things (and ugly). I think we might want to migrate to procedural macros at some point 😅

**Comment by f3r10** [comment]
I have just submitted the pull request: https://github.com/lambdaclass/lambda_ethereum_consensus/pull/81
