### ISSUE TITLE
Unblock state transition in fork choice

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#669]
Currently, fork choice genserver blocks when performing state transition. This will be solved by the per-block concurrency model, but in the meanwhile, we can solve the blocking part:

- We can start each state transition in an async task.
- We can handle the results in handle_info
- We can change the `handle_call` so that it does a `noreply` and then continues. This would mean that pending blocks still has a sync call to the store, but the store is not blocked for other uses like metadata, getting the head, etc. If not possible with handle_call, we can use a handle_cast + a receive from pending blocks, emulating an async call.

**Comment by MegaRedHand** [comment]
We fixed it as follows:
- BeaconChain GenServer caches forkchoice data
- `ForkChoice.on_block` is now async
- `PendingBlocks` fetches block data directly from DB
