### ISSUE TITLE
Rename `BlockStore` and `StateStore`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#686]
We should stop naming everything `Store`. For these cases I suggest the names `BlockDb` and `StateDb`

**Comment by mpaulucci** [comment]
Agreed!

**Comment by clionachee** [comment]
I'll fork and propose changes in name of BlockStore and StateStore to BlockDb and StateDb

**Comment by clionachee** [comment]
Made 1 change, and thanks @mpaulucci for telling me that we want to 'update the module everywhere where it's referenced'. I'll figure it out.
