### ISSUE TITLE
Add SSZ container: `SignedVoluntaryExit`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#70]
Depends on: #66

Follow these instructions: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md

#### `SignedVoluntaryExit`

```python
class SignedVoluntaryExit(Container):
    message: VoluntaryExit
    signature: BLSSignature
```

**Comment by h3lio5** [comment]
can I take this ser?

**Comment by MegaRedHand** [comment]
Go ahead! 😄
