### ISSUE TITLE
Add SSZ container: `SignedBeaconBlock`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#71]
Depends on: #68

Follow these instructions: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md

#### `SignedBeaconBlock`

```python
class SignedBeaconBlock(Container):
    message: BeaconBlock
    signature: BLSSignature
```

**Comment by Godspower-Eze** [comment]
I'll like to tackle this
