### ISSUE TITLE
Add NIF to use KZG functions

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#746]
See the Ethereum C implementation here: https://github.com/ethereum/c-kzg-4844/tree/main

We could either use the Rust bindings https://github.com/ethereum/c-kzg-4844/blob/main/bindings/rust/README.md with `rustler` or the C implementation.

The goal is to be able to make these tests pass: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/kzg

Functions to implement:
- `blob_to_kzg_commitment`
- `compute_kzg_proof`
- `compute_blob_kzg_proof`
- `verify_blob_kzg_proof`
- `verify_blob_kzg_proof_batch`

It might make sense to divide this ticket into one per function. Keeping it like this for now, but feel free to change it.

**Comment by Godspower-Eze** [comment]
I would like to work on this
