### ISSUE TITLE
Document `SszEx` schema format

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#815]
Since we have some special-cased types in our new SSZ module, we should document what each one does.

**Comment by f3r10** [comment]
@MegaRedHand, should the documentation be added in each of the public `encode` and `decode` functions of `SszEx`? :thinking:

**Comment by MegaRedHand** [comment]
Yes, but if you feel it's too verbose you can write it under `docs/`
