### ISSUE TITLE
`Erlang error: :snappy_nif_not_loaded` when running spec-tests

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#83]
From #82

> I am having a bug while trying to run make spec-test it creates this error trace:
> [test.txt](https://github.com/lambdaclass/lambda_ethereum_consensus/files/12432084/test.txt)

**Comment by mpaulucci** [comment]
I seems this old hasn't been reproed in a while. Closing, feel free to repoen
