### ISSUE TITLE
Attestation propagation

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#831]
An attesting validator should be broadcasted the attestation built in #803 , to the subnet designated by `compute_subnet_for_attestation(committees_per_slot, slot, committee_index)`.

Specs ref [here](https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/docs/specs/validator.md#broadcast-attestation)

Depends on #812 for testing

**Comment by MegaRedHand** [comment]
Already in main 🎉
