### ISSUE TITLE
SyncCommitteeMessage production

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#833]
In #800  `is_assigned_to_sync_committee` is coded, to evaluate, if at a single slot, a validator is part of a sync_committee and should send a message. This issue encompasses:

- Building a `SyncCommitteeMessage` using `get_sync_committee_message(state, block_root, validator_index, privkey)`.
- The message should be built and logged (mock broadcasting) if the current proposed block was received in the first slot interval or else if the interval has passed (empty slot).

spec ref: [link](https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/docs/specs/validator.md#sync-committee-messages)

**Comment by rodrigo-o** [comment]
Completed in #1280
