### ISSUE TITLE
SyncComitteeMessage broadcasting

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#834]
SyncCommittee messages should be broadcasted to the corresponding topic `sync_committee_{subnet_id}`, where subnet_id should be calculated using `compute_subnets_for_sync_committe(state, validator_index)`. Depends on #812 to be tested.

spec refs: [link](https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/docs/specs/validator.md#broadcast-sync-committee-message).

**Comment by rodrigo-o** [comment]
Completed in #1280
