### ISSUE TITLE
Implement `Bls.key_validate`

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#836]
We're missing a [KeyValidate implementation](https://github.com/ethereum/consensus-specs/blob/1a33bf8a00bb593d61a9128c929b8dcacef0b437/specs/phase0/beacon-chain.md?plain=1#L667) in the `Bls` module.

**Comment by guha-rahul** [comment]
hey can i work on this?

**Comment by mpaulucci** [comment]
assigned!

**Comment by guha-rahul** [comment]
hey after running the test and `make fmt` a lot of files got formatted to the configured style namely 
`        modified:   lib/bls.ex
        modified:   lib/lambda_ethereum_consensus/execution/rpc.ex
        modified:   lib/lambda_ethereum_consensus/state_transition/epoch_processing.ex
        modified:   lib/lambda_ethereum_consensus/state_transition/shuffling.ex
        modified:   lib/lambda_ethereum_consensus/store/lru_cache.ex
        modified:   lib/utils/bit_list.ex
        modified:   lib/utils/diff.ex
        modified:   native/bls_nif/src/lib.rs
        modified:   test/fixtures/block.ex
        modified:   test/spec/runners/bls.ex
        modified:   test/spec/runners/fork_choice.ex
        modified:   test/spec/runners/helpers/process_blocks.ex
        modified:   test/spec/runners/operations.ex
        modified:   test/spec/runners/ssz_static.ex
        modified:   test/spec/runners/sync.ex
        modified:   test/unit/req_resp_test.exs
        modified:   test/unit/snappy_test.exs
        `
        Am I supposed to discard those changes or commit them ?

**Comment by MegaRedHand** [comment]
That's weird 🤔. Can you please share some of those changes? Also, which elixir version are you using? (i.e. `elixir --version`)

I just tried it locally on `main` and it doesn't modify any files, so I guess it's some kind of misconfiguration.

**Comment by guha-rahul** [comment]
I am working with elixir 1.16.2. 

One of the changes that happened is 
![image](https://github.com/lambdaclass/lambda_ethereum_consensus/assets/52607971/298d8420-939f-4b7a-afc3-35576315340a)
(Sorry , I was unable to take a ss from my laptop)

**Comment by MegaRedHand** [comment]
Since they seem to be style changes, I say we discard them for now to simplify the review process. We can always add them later in a standalone PR 😄
