### ISSUE TITLE
Minimal valid SignedBeaconBlock construction

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#910]
This is part of https://github.com/lambdaclass/lambda_ethereum_consensus/issues/801

The idea it to create the simplest _valid_ block that can be propagated through the network.

So the scope for this block is:
- Compute starting state with `get_head`.
- Compute the parent root as `get_proposer_head(store, head_root, slot)`
- Set the block body with:
   - Compute `randao_reveal`
   - Copy `eth1_data` from previous block
   - Set all operations as empty lists (proposer slashing, attester slashing, pending attestations, etc..)
   - Call the execution layer with `get_execution_payload`.  Add KZG commitments returned from the execution layer to the blob
   - Calculate `sync_aggregate` as if no sync commitee contributions had been made
- Compute `compute_new_state_root`. Apply state transition to previous state and calculate the root to add it to the block.
- Sign the block.

**Comment by MegaRedHand** [comment]
The proposal should be done in https://github.com/lambdaclass/lambda_ethereum_consensus/blob/0e2858a39fec4789634412500cf8ae39905765be/lib/lambda_ethereum_consensus/validator/validator.ex#L398-L400
