### ISSUE TITLE
Calculate `eth1_data` for a block to be proposed

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#911]
Necessary reading: https://eth2book.info/capella/part2/deposits-withdrawals/deposit-processing/
Spec: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/docs/specs/validator.md#eth1-data

This required communicating with the Execution Client to fetch the deposit root to cast an `eth1_vote`.

I suggest looking at other client implementations for ideas. This task is non-trivial and one thing that has to be taken into account is how to handle this while the execution client is not synced with the tip of the chain.

Potencially can be divided into further tasks.

**Comment by MegaRedHand** [comment]
Blocked by #949 and #950
