### ISSUE TITLE
Make `BeaconChain` communicate ticks to other processes

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#926]
Currently, we communicate the passage of time to other processes in terms of blocks. We should move to using slots/fractions of a slot for that (e.g. in `Validator` it's important to send aggregates at the second third of a slot). This would also enable us to detect empty slots. Currently, we just fail to attest on those.

**Comment by mpaulucci** [comment]
🎉
