### ISSUE TITLE
Normalize error messages in SszEx library

### ISSUE THREAD

**Issue by avilagaston9** [lambdaclass/lambda_ethereum_consensus#986]
Currently, some error messages in the SszEx library are in CamelCase while others just don't follow any rule.
We can also make them more specific to indicate the exact field where the error occurs.
_Originally posted by @mpaulucci in https://github.com/lambdaclass/lambda_ethereum_consensus/pull/983#discussion_r1566035827_

**Comment by MegaRedHand** [comment]
A good way to improve errors is to define an error struct on the interface, like this:
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/f3d6067924ecd65abdefcbf23cbcbea0c1d75d13/lib/lambda_ethereum_consensus/p2p/req_resp.ex#L10-L29
